### PR TITLE
Add mode switcher using touchscreen gestures

### PR DESCRIPTION
**Pull request by Smart123s**
This should fix https://github.com/dvlden/ultrawideo/issues/15

Todo: Write tests

Tested on: 
- Firefox Nightly (v201228 17:01)
- Android 11
- YouTube

Pinch in to go to the next mode (in the order found in [defaults.js](https://github.com/dvlden/ultrawideo/blob/main/src/scripts/static/defaults.js))
Pinch out to go back to the previous mode.
Note: Pinch out won't go to stretched mode after normal, but zoom in will go to stretched after normal

There are some typos in my commit message, sorry about that. :)

### CODE REVIEW

**Comment by Smart123s** [comment]
I've just realized that I had broken some of the original test by renaming a function. I'll fix that fast.

**Comment by Smart123s** [comment]
This should be ready for review (and merging).
I haven't changed the version number, should it be changed?

**Comment by dvlden** [comment]
Hello @Smart123s ,

Thanks A LOT for this PR. I did not see it on time due to holidays, which are still on-going in Serbia. 
Let me review it right away and I'll either merge it or comment if I notice anything that would need a slight change. 

No, version number is okay as is for now.

**Comment by dvlden** [comment]
Looks good. Here and there, some slight indentation issues, but overall I love it. 
Thanks for this big effort, especially for writing the tests along with this new feature!

I am merging this right away! 👍 💯

**Comment by Smart123s** [comment]
Thanks a lot for reviewing and merging it, I am really looking forward to zoom into YouTube videos on my phone. I hope you had a good holiday. 🙂

**Comment by dvlden** [comment]
The extension has been submitted to the Firefox and Chrome stores, with your awesome implementation that I did not test, because I fully trust your contribution and test coverage has got it all. 

Thank you once again for this amazing PR. 🥰

**Comment by Smart123s** [comment]
I had to reinstall the extension (maybe Firefox had forgotten to update it 😃), but I can confirm that it's working.
I've only tested it on YouTube on Firefox, but it _should_ work on other platforms as well.

Thank you again for adding this feature into your extension. And thank you for trusting me. 😍

Here's a video showcasing the gestures. I don't know why I haven't posted one earlier to show that it's actually working.

https://user-images.githubusercontent.com/28480228/104116959-9b530b80-531d-11eb-9783-20755b1fca78.mp4

**Comment by dvlden** [comment]
Oh my, that showcase is awesome! You did great job!

**Pull request merged**
